export interface Note {
  top: string[];
  middle: string[];
  base: string[];
}

export interface Accord {
  nama: string;
  persen: number;
}

export type Gender = "Pria" | "Wanita" | "Unisex";
export type WaktuPakai = "Pagi" | "Siang" | "Sore" | "Malam";

export interface Product {
  slug: string;
  nama: string;
  grade: "Premium" | "Medium";
  gender: Gender;
  waktuPakai: WaktuPakai[];
  hargaMulai: number;
  volumeTersedia: number[];
  ringkasan: string;
  deskripsi: string;
  notes: Note;
  mainAccords: Accord[];
  fragranticaUrl?: string;
  bottleColor: string;
}

export const WHATSAPP_NUMBER = "628990447098";

// Harga mulai seragam untuk semua racikan
export const HARGA_MULAI_DEFAULT = 20000;

// Ukuran botol seragam untuk semua racikan. 100ml tidak dijual reguler,
// tapi bisa direquest lewat WhatsApp (lihat VOLUME_REQUEST di halaman produk).
export const VOLUME_TERSEDIA_DEFAULT = [15, 20, 30, 50];
export const VOLUME_REQUEST = 100;

export function whatsappOrderUrl(namaProduk: string) {
  const pesan = [
    `Halo Arung Wangi, saya mau pesan racikan *${namaProduk}*.`,
    "",
    "Format pesanan saya:",
    "Nama:",
    "Ukuran (ml):",
    "Jumlah:",
    "Alamat:",
    "",
    "Mohon info total harga & cara pembayarannya. Terima kasih!",
  ].join("\n");
  return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(pesan)}`;
}

export function whatsappGeneralUrl() {
  const pesan = [
    "Halo Arung Wangi, saya mau tanya-tanya / pesan racikan.",
    "",
    "Format pesanan saya:",
    "Nama:",
    "Racikan yang diminati:",
    "Ukuran (ml):",
    "Jumlah:",
    "Alamat:",
    "",
    "Terima kasih!",
  ].join("\n");
  return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(pesan)}`;
}

export const products: Product[] = [
  {
    slug: "verdant-fig",
    nama: "Verdant Fig",
    grade: "Premium",
    gender: "Unisex",
    waktuPakai: ["Sore", "Malam"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Hijau, earthy, dan sedikit smoky — seperti hutan basah selepas hujan.",
    deskripsi:
      "Racikan woody-aromatic yang membuka dengan buah ara hijau dan teh matcha, diselingi asap kemenyan dan kayu manis halus. Di tengah, cashmere wood dan jeruk memberi sentuhan creamy-citrus sebelum turun ke vetiver, cendana, dan cedar yang earthy — mengingatkan pada tanah basah dan dedaunan setelah hujan. Cocok untuk yang suka aroma tenang, natural, dan tidak terlalu manis.",
    notes: {
      top: ["Kemenyan", "Kayu Manis", "Teh Matcha", "Bergamot", "Buah Ara"],
      middle: ["Orcanox", "Cashmere Wood", "Jeruk"],
      base: ["Vetiver", "Cedar", "Cendana"],
    },
    mainAccords: [
      { nama: "Woody", persen: 88 },
      { nama: "Earthy", persen: 72 },
      { nama: "Green", persen: 60 },
      { nama: "Smoky", persen: 45 },
      { nama: "Milky", persen: 35 },
      { nama: "Citrus", persen: 28 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Mykonos/Down-to-Earth-120471.html",
    bottleColor: "#3d4a2f",
  },
  {
    slug: "rose-bergamot",
    nama: "Rosé Bergamot",
    grade: "Premium",
    gender: "Unisex",
    waktuPakai: ["Siang", "Sore"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Citrus cerah bertemu mawar dan buah-buahan — mewah ala French Riviera.",
    deskripsi:
      "Dibuka dengan bergamot, jeruk, dan lemon yang segar, racikan ini mengalir ke jantung mawar yang dipadukan aprikot, raspberry, dan plum — manis tapi tidak berlebihan. Ambrette memberi kesan bersih sebelum mengendap di cedar, vetiver, amber, dan musk yang hangat. Cocok dipakai siang ke malam, untuk yang suka kesan glamor tanpa terlalu berat.",
    notes: {
      top: ["Bergamot", "Jeruk", "Melati", "Lemon"],
      middle: ["Mawar", "Aprikot", "Raspberry", "Ambrette", "Plum"],
      base: ["Cedar", "Vetiver", "Amber", "Musk"],
    },
    mainAccords: [
      { nama: "Floral", persen: 85 },
      { nama: "Fruity", persen: 70 },
      { nama: "Citrus", persen: 62 },
      { nama: "Musky", persen: 40 },
      { nama: "Woody", persen: 32 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Mykonos/Monaco-Royale-121113.html",
    bottleColor: "#a8586b",
  },
  {
    slug: "praline-tonka",
    nama: "Praline Tonka",
    grade: "Medium",
    gender: "Unisex",
    waktuPakai: ["Pagi", "Siang"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Manis creamy seperti tiramisu, dengan kopi yang muncul samar di baliknya.",
    deskripsi:
      "Gourmand manis yang membuka dengan aroma kopi lembut berpadu anggrek dan melati, lalu mengalir ke vanilla-susu yang creamy dan karamel — mengingatkan pada tiramisu segar. Amber, patchouli, dan musk di dasar memberi sedikit kehangatan tanpa menutupi kesan manis-milky-nya. Ringan dan playful, cocok dipakai harian untuk yang suka wangi manis.",
    notes: {
      top: ["Kopi", "Anggrek", "Melati"],
      middle: ["Vanilla", "Susu", "Tonka Bean", "Karamel"],
      base: ["Amber", "Patchouli", "Musk"],
    },
    mainAccords: [
      { nama: "Sweet", persen: 90 },
      { nama: "Vanilla", persen: 82 },
      { nama: "Milky", persen: 68 },
      { nama: "Coffee", persen: 45 },
      { nama: "Caramel", persen: 40 },
      { nama: "Musky", persen: 30 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Mykonos/Cafe-Drops-120463.html",
    bottleColor: "#a67c4a",
  },
  {
    slug: "iris-amber",
    nama: "Iris Amber",
    grade: "Premium",
    gender: "Unisex",
    waktuPakai: ["Siang", "Sore"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Floral-woody lembut dengan sentuhan bedak — elegan dan tenang.",
    deskripsi:
      "Racikan floral-woody-musk yang membuka dengan mandarin dan daun violet segar, mengalir ke jantung iris berbedak dan freesia yang lembut, dibalut cedarwood. Di dasar, tonka bean, amber, dan vetiver memberi kehangatan yang tenang tanpa berat. Elegan dan halus, cocok untuk yang suka wangi 'bersih' tapi tetap berkarakter.",
    notes: {
      top: ["Mandarin", "Daun Violet", "Bergamot"],
      middle: ["Iris", "Cedarwood", "Freesia"],
      base: ["Tonka Bean", "Amber", "Vetiver"],
    },
    mainAccords: [
      { nama: "Floral", persen: 82 },
      { nama: "Woody", persen: 75 },
      { nama: "Musky", persen: 60 },
      { nama: "Powdery", persen: 45 },
      { nama: "Amber", persen: 38 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/SAFF-Co/Solaris-98616.html",
    bottleColor: "#7c6a8a",
  },
  {
    slug: "bergamot-chai",
    nama: "Bergamot Chai",
    grade: "Premium",
    gender: "Unisex",
    waktuPakai: ["Pagi", "Siang"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Citrus cerah bertemu teh hitam dan jahe — segar dan membangunkan.",
    deskripsi:
      "Dibuka dengan lemon, jahe, bergamot, dan jeruk yang tajam-segar, racikan ini mengalir ke teh hitam dan kayu manis di tengah — seperti secangkir chai hangat. Neroli menjaga kesan segarnya sebelum mengendap di musk, cedarwood, dan guaiac wood yang woody-bersih. Cocok dipakai pagi hari, membangunkan mood sebelum beraktivitas.",
    notes: {
      top: ["Lemon", "Jahe", "Bergamot", "Jeruk"],
      middle: ["Teh Hitam", "Kayu Manis", "Neroli"],
      base: ["Musk", "Cedarwood", "Guaiac Wood"],
    },
    mainAccords: [
      { nama: "Citrus", persen: 85 },
      { nama: "Fresh", persen: 70 },
      { nama: "Rempah", persen: 50 },
      { nama: "Woody", persen: 45 },
      { nama: "Musky", persen: 30 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Mykonos/Inception-121107.html",
    bottleColor: "#a3572a",
  },
  {
    slug: "apricot-rose",
    nama: "Apricot Rose",
    grade: "Premium",
    gender: "Unisex",
    waktuPakai: ["Siang", "Sore"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Fruity-floral manis — grapefruit dan aprikot bertemu mawar dan melati.",
    deskripsi:
      "Racikan fruity-floral-gourmand yang membuka dengan grapefruit, bergamot, jeruk, dan lemon segar. Jantungnya penuh — patchouli, raspberry, melati, aprikot, mawar, dan lily — manis tanpa berlebihan. Di dasar, cendana, cedarwood, vanilla, amber, dan musk memberi kehangatan yang membekas. Charming dan playful, cocok untuk yang suka wangi manis tapi tetap kompleks.",
    notes: {
      top: ["Buah-buahan", "Grapefruit", "Bergamot", "Jeruk", "Lemon"],
      middle: ["Patchouli", "Raspberry", "Melati", "Aprikot", "Mawar", "Lily"],
      base: ["Cendana", "Cedarwood", "Vanilla", "Amber", "Musk"],
    },
    mainAccords: [
      { nama: "Fruity", persen: 88 },
      { nama: "Floral", persen: 72 },
      { nama: "Sweet", persen: 55 },
      { nama: "Woody", persen: 42 },
      { nama: "Musky", persen: 30 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Mykonos/Utopia-121138.html",
    bottleColor: "#d68a52",
  },
  {
    slug: "lavender-marine",
    nama: "Lavender Marine",
    grade: "Medium",
    gender: "Unisex",
    waktuPakai: ["Pagi", "Siang"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Aromatic-aquatic segar — lavender, garam laut, dan bunga air.",
    deskripsi:
      "Racikan aromatic-aquatic yang membuka dengan lavender, grapefruit, pir, dan sentuhan garam laut. Jantungnya aquatic — marine notes, water flowers, dan rhubarb — segar seperti angin pantai. Di dasar, karamel tipis, woody notes, dan moss memberi sedikit kehangatan tanpa menghilangkan kesan segarnya. Cocok untuk aktivitas outdoor dan cuaca panas.",
    notes: {
      top: ["Lavender", "Grapefruit", "Pir", "Garam Laut"],
      middle: ["Marine Notes", "Water Flowers", "Rhubarb"],
      base: ["Karamel", "Woody Notes", "Moss"],
    },
    mainAccords: [
      { nama: "Aquatic", persen: 85 },
      { nama: "Fresh", persen: 72 },
      { nama: "Green", persen: 45 },
      { nama: "Sweet", persen: 35 },
      { nama: "Woody", persen: 30 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Mykonos/California-Blue-120464.html",
    bottleColor: "#2f6b7a",
  },
  {
    slug: "cardamom-amber",
    nama: "Cardamom Amber",
    grade: "Premium",
    gender: "Pria",
    waktuPakai: ["Sore", "Malam"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Oriental woody gelap — praline dan kayu manis bertemu amber hitam.",
    deskripsi:
      "Racikan oriental-woody yang membuka dengan lemon dan sage tajam, lalu turun ke jantung praline, kayu manis, tolu balsam, dan kapulaga hitam yang manis-hangat. Di dasar, patchouli, kayu rosewood, dan black amber memberi kesan gelap dan maskulin yang membekas lama. Bold dan tegas, cocok untuk malam hari atau acara formal.",
    notes: {
      top: ["Lemon", "Sage"],
      middle: ["Praline", "Kayu Manis", "Tolu Balsam", "Kapulaga Hitam"],
      base: ["Patchouli", "Kayu Rosewood", "Black Amber"],
    },
    mainAccords: [
      { nama: "Sweet", persen: 80 },
      { nama: "Rempah", persen: 68 },
      { nama: "Woody", persen: 55 },
      { nama: "Amber", persen: 50 },
      { nama: "Balsamic", persen: 35 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Rabanne/Black-XS-514.html",
    bottleColor: "#4a2a1f",
  },
  {
    slug: "bergamot-ambroxan",
    nama: "Bergamot Ambroxan",
    grade: "Premium",
    gender: "Pria",
    waktuPakai: ["Pagi", "Siang", "Sore"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Segar, amber-woody, dan serbaguna — cocok dipakai kapan saja.",
    deskripsi:
      "Racikan amber-woody-aromatic yang membuka dengan bergamot Calabria dan sentuhan lada segar. Jantungnya aromatic-spicy — lada Sichuan, lavender, pink pepper, vetiver, patchouli, geranium, dan elemi — sebelum mengendap di ambroxan, cedar, dan labdanum yang bersih dan membekas ringan. Serbaguna, cocok dipakai dari pagi sampai sore untuk aktivitas apa saja.",
    notes: {
      top: ["Bergamot Calabria", "Lada"],
      middle: ["Lada Sichuan", "Lavender", "Pink Pepper", "Vetiver", "Patchouli", "Geranium", "Elemi"],
      base: ["Ambroxan", "Cedar", "Labdanum"],
    },
    mainAccords: [
      { nama: "Citrus", persen: 80 },
      { nama: "Amber", persen: 70 },
      { nama: "Woody", persen: 60 },
      { nama: "Rempah", persen: 45 },
      { nama: "Fresh", persen: 40 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Dior/Sauvage-31861.html",
    bottleColor: "#5a6b6e",
  },
  {
    slug: "cinnamon-oud",
    nama: "Cinnamon Oud",
    grade: "Premium",
    gender: "Unisex",
    waktuPakai: ["Sore", "Malam"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Oriental spicy gourmand — praline hangat bertemu oud manis dan kemenyan.",
    deskripsi:
      "Racikan oriental yang membuka dengan bergamot dan kayu manis, mengalir ke jantung praline creamy dan tuberose, lalu mengendap di oud manis, kemenyan, dan tonka bean yang hangat membekas. Mewah dan bold, cocok untuk malam hari atau cuaca dingin.",
    notes: {
      top: ["Bergamot", "Kayu Manis", "Clary Sage"],
      middle: ["Praline", "Tuberose", "Buah Manis"],
      base: ["Oud Manis", "Kemenyan", "Tonka Bean", "Vanilla"],
    },
    mainAccords: [
      { nama: "Sweet", persen: 90 },
      { nama: "Rempah", persen: 78 },
      { nama: "Vanilla", persen: 65 },
      { nama: "Amber", persen: 50 },
      { nama: "Woody", persen: 40 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Khamrah-75805.html",
    bottleColor: "#6b3a1f",
  },
  {
    slug: "ginger-ambroxan",
    nama: "Ginger Ambroxan",
    grade: "Premium",
    gender: "Pria",
    waktuPakai: ["Pagi", "Siang"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Citrus aromatic — jeruk sisilia bertemu jahe dan teh hitam.",
    deskripsi:
      "Racikan citrus-aromatic yang membuka dengan citron, bergamot Calabria, dan jeruk Sisilia. Jantungnya hangat — neroli, jahe, dan kayu manis Ceylon — sebelum mengendap di teh hitam, ambroxan, guaiac wood, dan kemenyan yang bersih maskulin. Elegan dan modern, cocok untuk kerja atau acara formal siang hari.",
    notes: {
      top: ["Citron", "Bergamot Calabria", "Jeruk Sisilia"],
      middle: ["Neroli", "Jahe", "Kayu Manis Ceylon"],
      base: ["Teh Hitam", "Ambroxan", "Guaiac Wood", "Kemenyan"],
    },
    mainAccords: [
      { nama: "Citrus", persen: 82 },
      { nama: "Amber", persen: 70 },
      { nama: "Woody", persen: 55 },
      { nama: "Rempah", persen: 40 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Louis-Vuitton/Imagination-67370.html",
    bottleColor: "#8a6a3f",
  },
  {
    slug: "pineapple-birch",
    nama: "Pineapple Birch",
    grade: "Premium",
    gender: "Pria",
    waktuPakai: ["Pagi", "Siang", "Sore"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Fruity chypre ikonik — nanas segar bertemu birch dan musk hangat.",
    deskripsi:
      "Racikan fruity-chypre yang membuka dengan bergamot, blackcurrant, apel, dan nanas yang juicy. Jantungnya pink pepper, birch, patchouli, dan jasmine, sebelum mengendap di musk, oakmoss, ambergris, dan vanilla yang hangat membekas lama. Serbaguna dan ikonik, cocok dipakai kapan saja.",
    notes: {
      top: ["Bergamot", "Blackcurrant", "Apel", "Nanas"],
      middle: ["Pink Pepper", "Birch", "Patchouli", "Jasmine"],
      base: ["Musk", "Oakmoss", "Ambergris", "Vanilla"],
    },
    mainAccords: [
      { nama: "Fruity", persen: 88 },
      { nama: "Woody", persen: 65 },
      { nama: "Musky", persen: 55 },
      { nama: "Sweet", persen: 40 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Creed/Aventus-9828.html",
    bottleColor: "#5c4630",
  },
  {
    slug: "mint-tonka",
    nama: "Mint Tonka",
    grade: "Medium",
    gender: "Pria",
    waktuPakai: ["Pagi", "Siang"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Segar dan manis — mint, apel hijau, bertemu tonka bean hangat.",
    deskripsi:
      "Racikan fresh-gourmand yang membuka dengan mint, apel hijau, dan lemon yang energik. Jantungnya tonka bean, ambroxan, geranium, dan mawar memberi kehangatan, sebelum mengendap di vanilla, vetiver, oakmoss, dan cedarwood. Ringan dan mudah dipakai, cocok untuk aktivitas harian.",
    notes: {
      top: ["Mint", "Apel Hijau", "Lemon"],
      middle: ["Tonka Bean", "Ambroxan", "Geranium", "Mawar"],
      base: ["Vanilla", "Vetiver", "Oakmoss", "Cedarwood"],
    },
    mainAccords: [
      { nama: "Fresh", persen: 85 },
      { nama: "Sweet", persen: 70 },
      { nama: "Woody", persen: 50 },
      { nama: "Citrus", persen: 40 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Versace/Eros-16657.html",
    bottleColor: "#3a6b4a",
  },
  {
    slug: "plum-driftwood",
    nama: "Plum Driftwood",
    grade: "Medium",
    gender: "Pria",
    waktuPakai: ["Pagi", "Siang"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Fresh fruity aquatic — apel dan bergamot bertemu driftwood musky.",
    deskripsi:
      "Racikan fresh-fruity yang membuka dengan apel, lemon Italia, bergamot Sisilia, dan star anise. Jantungnya plum, bunga jeruk, dan kapulaga, sebelum mengendap di musk, amber, driftwood, dan moss yang bersih. Cocok untuk cuaca panas dan aktivitas outdoor.",
    notes: {
      top: ["Apel", "Lemon Italia", "Bergamot Sisilia", "Star Anise"],
      middle: ["Plum", "Bunga Jeruk", "Kapulaga"],
      base: ["Musk", "Amber", "Driftwood", "Moss"],
    },
    mainAccords: [
      { nama: "Fresh", persen: 82 },
      { nama: "Fruity", persen: 68 },
      { nama: "Aquatic", persen: 55 },
      { nama: "Woody", persen: 35 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Rasasi/Hawas-Ice-89050.html",
    bottleColor: "#4a6b6b",
  },
  {
    slug: "saffron-ambergris",
    nama: "Saffron Ambergris",
    grade: "Premium",
    gender: "Unisex",
    waktuPakai: ["Sore", "Malam"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Amber ikonik — saffron dan jasmine bertemu kayu manis-gula.",
    deskripsi:
      "Racikan amber-floral yang membuka dengan saffron dan jasmine yang breezy. Jantungnya amberwood, ambergris, dan hedione memberi kesan mineral, sebelum mengendap di fir resin, cedar, gula, ambroxan, dan oakmoss yang manis-hangat. Mewah dan memorable, cocok dipakai sore ke malam.",
    notes: {
      top: ["Saffron", "Jasmine"],
      middle: ["Amberwood", "Ambergris", "Hedione"],
      base: ["Fir Resin", "Cedar", "Gula", "Ambroxan", "Oakmoss"],
    },
    mainAccords: [
      { nama: "Amber", persen: 92 },
      { nama: "Sweet", persen: 70 },
      { nama: "Woody", persen: 55 },
      { nama: "Floral", persen: 45 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/Baccarat-Rouge-540-33519.html",
    bottleColor: "#c9973f",
  },
  {
    slug: "midnight-coffee",
    nama: "Midnight Coffee",
    grade: "Premium",
    gender: "Wanita",
    waktuPakai: ["Sore", "Malam"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Gourmand gelap — kopi pekat bertemu vanilla dan rempah manis.",
    deskripsi:
      "Racikan oriental-gourmand yang membuka dengan buah-buahan, bunga, dan pink pepper. Jantungnya kopi pekat dan melati, sebelum mengendap di vanilla, patchouli, dan cedar yang gelap-seduktif. Lebih bold dan dramatis dibanding Praline Tonka, cocok dipakai malam hari.",
    notes: {
      top: ["Buah-buahan", "Bunga Jeruk", "Pink Pepper"],
      middle: ["Kopi", "Melati"],
      base: ["Vanilla", "Patchouli", "Cedar"],
    },
    mainAccords: [
      { nama: "Sweet", persen: 88 },
      { nama: "Coffee", persen: 75 },
      { nama: "Vanilla", persen: 70 },
      { nama: "Rempah", persen: 45 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Black-Opium-25324.html",
    bottleColor: "#2a1f1a",
  },
  {
    slug: "pear-musk",
    nama: "Pear Musk",
    grade: "Premium",
    gender: "Unisex",
    waktuPakai: ["Pagi", "Siang"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Fruity musky — pir juicy bertemu musk lembut dan cedar.",
    deskripsi:
      "Racikan fruity-musky yang membuka dengan pir, bergamot, jeruk mandarin, dan jahe segar. Jantungnya bunga jeruk dan georgywood, sebelum mengendap di musk, ambrofix, dan cedar yang airy. Ringan dan clean, cocok dipakai harian.",
    notes: {
      top: ["Pir", "Bergamot", "Jeruk Mandarin", "Jahe"],
      middle: ["Bunga Jeruk", "Georgywood"],
      base: ["Musk", "Ambrofix", "Akigalawood", "Cedar"],
    },
    mainAccords: [
      { nama: "Fruity", persen: 85 },
      { nama: "Musky", persen: 72 },
      { nama: "Woody", persen: 45 },
      { nama: "Fresh", persen: 35 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Ex-Nihilo/Blue-Talisman-84224.html",
    bottleColor: "#7a8a9a",
  },
  {
    slug: "cherry-almond",
    nama: "Cherry Almond",
    grade: "Premium",
    gender: "Unisex",
    waktuPakai: ["Sore", "Malam"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Gourmand fruity — ceri hitam pekat bertemu almond dan mawar.",
    deskripsi:
      "Racikan gourmand yang membuka dengan ceri hitam, cherry liqueur, dan almond pahit yang tajam. Jantungnya griotte syrup, mawar Turki, dan melati Sambac, sebelum mengendap di peru balm, tonka panggang, cendana, dan cedar yang hangat membekas. Manis dan memikat, cocok dipakai malam hari.",
    notes: {
      top: ["Ceri Hitam", "Cherry Liqueur", "Almond Pahit"],
      middle: ["Griotte Syrup", "Mawar Turki", "Melati Sambac"],
      base: ["Peru Balm", "Tonka Panggang", "Cendana", "Vetiver", "Cedar"],
    },
    mainAccords: [
      { nama: "Sweet", persen: 90 },
      { nama: "Fruity", persen: 78 },
      { nama: "Floral", persen: 50 },
      { nama: "Woody", persen: 40 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Tom-Ford/Lost-Cherry-51411.html",
    bottleColor: "#6b1f2a",
  },
  {
    slug: "green-apple-lotus",
    nama: "Green Apple Lotus",
    grade: "Medium",
    gender: "Pria",
    waktuPakai: ["Pagi", "Siang"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Woody aquatic segar — apel hijau bertemu water lotus dan cedar.",
    deskripsi:
      "Racikan woody-aquatic yang membuka dengan apel hijau dan daun hijau yang crisp. Jantungnya sailcloth accord, mimosa basah, dan water lotus, sebelum mengendap di moss, cedarwood, amber, dan musk yang hangat. Segar dan bold, cocok untuk aktivitas outdoor.",
    notes: {
      top: ["Apel Hijau", "Daun Hijau"],
      middle: ["Sailcloth Accord", "Mimosa", "Water Lotus"],
      base: ["Moss", "Cedarwood", "Amber", "Musk"],
    },
    mainAccords: [
      { nama: "Aquatic", persen: 85 },
      { nama: "Fresh", persen: 70 },
      { nama: "Green", persen: 45 },
      { nama: "Woody", persen: 40 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Nautica/Nautica-Voyage-913.html",
    bottleColor: "#2f6b5a",
  },
  {
    slug: "pineapple-patchouli",
    nama: "Pineapple Patchouli",
    grade: "Premium",
    gender: "Unisex",
    waktuPakai: ["Pagi", "Siang", "Sore"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Fruity fresh woody — nanas tropis bertemu patchouli dan cedar.",
    deskripsi:
      "Racikan fruity-woody yang membuka dengan nanas, grapefruit, dan bergamot yang cerah tropis. Jantungnya cedar, patchouli, dan melati, sebelum mengendap di oakmoss dan woody notes yang earthy. Segar dan serbaguna, cocok dipakai sepanjang hari.",
    notes: {
      top: ["Nanas", "Grapefruit", "Bergamot"],
      middle: ["Cedar", "Patchouli", "Melati"],
      base: ["Oakmoss", "Woody Notes"],
    },
    mainAccords: [
      { nama: "Fruity", persen: 85 },
      { nama: "Citrus", persen: 65 },
      { nama: "Woody", persen: 55 },
      { nama: "Green", persen: 30 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Nishane/Hacivat-44174.html",
    bottleColor: "#7a9a3a",
  },
  {
    slug: "lychee-rose",
    nama: "Lychee Rose",
    grade: "Premium",
    gender: "Wanita",
    waktuPakai: ["Siang", "Sore"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Floral rose mewah — litchi juicy bertemu mawar Turki dan karamel.",
    deskripsi:
      "Racikan floral yang membuka dengan litchi, rhubarb, bergamot, pala, dan blackcurrant. Jantungnya mawar Turki, peony, dan musk, sebelum mengendap di cashmeran, kemenyan, cedar, vetiver Haiti, dan karamel yang manis-hangat. Elegan dan feminin, cocok dipakai siang ke malam.",
    notes: {
      top: ["Litchi", "Rhubarb", "Bergamot", "Pala", "Blackcurrant"],
      middle: ["Mawar Turki", "Peony", "Musk", "Petalia", "Vanilla"],
      base: ["Cashmeran", "Kemenyan", "Cedar", "Vetiver Haiti", "Karamel"],
    },
    mainAccords: [
      { nama: "Floral", persen: 90 },
      { nama: "Fruity", persen: 60 },
      { nama: "Sweet", persen: 50 },
      { nama: "Musky", persen: 40 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Parfums-de-Marly/Delina-43871.html",
    bottleColor: "#c26b7a",
  },
  {
    slug: "apple-caramel",
    nama: "Apple Caramel",
    grade: "Medium",
    gender: "Unisex",
    waktuPakai: ["Sore", "Malam"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Fruity woody manis — apel bertemu cedarwood dan karamel hangat.",
    deskripsi:
      "Racikan fruity-woody yang membuka dengan nanas, apel Granny Smith, dan mandarin. Jantungnya oakmoss, cedarwood, dan vanilla, sebelum mengendap di dry wood, ambergris, karamel, dan musk yang manis. Playful dan mysterious, cocok dipakai malam hari.",
    notes: {
      top: ["Nanas", "Apel Granny Smith", "Mandarin"],
      middle: ["Oakmoss", "Cedarwood", "Vanilla"],
      base: ["Dry Wood", "Ambergris", "Karamel", "Musk"],
    },
    mainAccords: [
      { nama: "Fruity", persen: 80 },
      { nama: "Sweet", persen: 65 },
      { nama: "Woody", persen: 55 },
      { nama: "Musky", persen: 35 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Afnan/9-PM-Rebel-99238.html",
    bottleColor: "#7a5a3a",
  },
  {
    slug: "golden-ylang",
    nama: "Golden Ylang",
    grade: "Premium",
    gender: "Wanita",
    waktuPakai: ["Siang", "Sore"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Floral ikonik — jasmine dan ylang-ylang bertemu mawar Damaskus.",
    deskripsi:
      "Racikan floral yang membuka dengan mandarin segar, mengalir ke jantung penuh — melati, plum, anggrek, mawar Damaskus, dan ylang-ylang — sebelum mengendap di musk, blackberry, dan amaranth. Luminous dan opulent, klasik untuk siapapun yang suka floral kompleks.",
    notes: {
      top: ["Mandarin"],
      middle: ["Melati", "Plum", "Anggrek", "Mawar Damaskus", "Ylang-Ylang"],
      base: ["Musk", "Blackberry", "Amaranth"],
    },
    mainAccords: [
      { nama: "Floral", persen: 92 },
      { nama: "Fruity", persen: 45 },
      { nama: "Musky", persen: 40 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Dior/J-adore-210.html",
    bottleColor: "#c9a63f",
  },
  {
    slug: "velvet-rose",
    nama: "Velvet Rose",
    grade: "Premium",
    gender: "Wanita",
    waktuPakai: ["Sore", "Malam"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Floral powdery intens — litchi manis bertemu mawar Damaskus dan musk.",
    deskripsi:
      "Racikan floral yang lebih intens dan powdery — litchi manis membuka, lalu mawar Damaskus pekat mengambil alih, dibalut amber yang misterius. Di dasar, vanilla bedak dan musk putih memberi kesan clean-sensual. Lebih smoky dan sweet dibanding Lychee Rose, cocok untuk cuaca dingin.",
    notes: {
      top: ["Litchi", "Bergamot"],
      middle: ["Mawar Damaskus", "Amber"],
      base: ["Vanilla Bedak", "Musk Putih"],
    },
    mainAccords: [
      { nama: "Floral", persen: 88 },
      { nama: "Sweet", persen: 75 },
      { nama: "Powdery", persen: 55 },
      { nama: "Amber", persen: 40 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Parfums-de-Marly/Delina-Exclusif-50370.html",
    bottleColor: "#8a4a5a",
  },
  {
    slug: "pistachio-gelato",
    nama: "Pistachio Gelato",
    grade: "Medium",
    gender: "Unisex",
    waktuPakai: ["Siang", "Sore"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Gourmand dessert — pistachio dan es krim bertemu whipped cream manis.",
    deskripsi:
      "Racikan gourmand yang membuka dengan pistachio, es krim, hazelnut, dan rum yang manis nutty. Jantungnya pir, melati, dan raspberry, sebelum mengendap di whipped cream, tonka bean, dan cacao yang creamy membekas. Fun dan addictive, cocok untuk yang suka wangi seperti dessert.",
    notes: {
      top: ["Pistachio", "Es Krim", "Hazelnut", "Rum"],
      middle: ["Pir", "Melati", "Raspberry"],
      base: ["Whipped Cream", "Tonka Bean", "Cacao"],
    },
    mainAccords: [
      { nama: "Sweet", persen: 95 },
      { nama: "Milky", persen: 80 },
      { nama: "Fruity", persen: 50 },
      { nama: "Woody", persen: 30 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Kayali-Fragrances/Yum-Pistachio-Gelato-33-79846.html",
    bottleColor: "#9a8a5a",
  },
  {
    slug: "pear-freesia",
    nama: "Pear Freesia",
    grade: "Premium",
    gender: "Unisex",
    waktuPakai: ["Pagi", "Siang"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Fruity chypre klasik — pir segar bertemu freesia dan mawar.",
    deskripsi:
      "Racikan fruity-chypre yang membuka dengan pir dan melon yang segar. Jantungnya freesia dan mawar lembut, sebelum mengendap di musk, amber, patchouli, dan rhubarb yang clean. Elegan dan ringan, cocok dipakai harian.",
    notes: {
      top: ["Pir", "Melon"],
      middle: ["Freesia", "Mawar"],
      base: ["Musk", "Amber", "Patchouli", "Rhubarb"],
    },
    mainAccords: [
      { nama: "Fruity", persen: 85 },
      { nama: "Floral", persen: 60 },
      { nama: "Musky", persen: 40 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Jo-Malone-London/English-Pear-Freesia-10314.html",
    bottleColor: "#a8b86a",
  },
  {
    slug: "hazelnut-amberwood",
    nama: "Hazelnut Amberwood",
    grade: "Medium",
    gender: "Pria",
    waktuPakai: ["Sore", "Malam"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Woody gourmand — hazelnut dan madu bertemu amberwood hangat.",
    deskripsi:
      "Racikan woody-gourmand yang membuka dengan plum, ozonic notes, grapefruit, dan bergamot. Jantungnya hazelnut, madu, cedar, cashmere wood, dan melati, sebelum mengendap di amberwood, patchouli, vetiver, dan oakmoss yang hangat sensual. Vivid dan captivating, cocok dipakai malam hari.",
    notes: {
      top: ["Plum", "Ozonic Notes", "Grapefruit", "Bergamot"],
      middle: ["Hazelnut", "Madu", "Cedar", "Cashmere Wood", "Melati"],
      base: ["Amberwood", "Patchouli", "Vetiver", "Oakmoss"],
    },
    mainAccords: [
      { nama: "Woody", persen: 82 },
      { nama: "Sweet", persen: 65 },
      { nama: "Fruity", persen: 45 },
      { nama: "Fresh", persen: 35 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Rabanne/1-Million-Lucky-48903.html",
    bottleColor: "#5c4020",
  },
  {
    slug: "rose-espresso",
    nama: "Rose Espresso",
    grade: "Premium",
    gender: "Unisex",
    waktuPakai: ["Sore", "Malam"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Oriental vanilla — kopi pekat bertemu mawar dan amber hangat.",
    deskripsi:
      "Racikan oriental-vanilla yang membuka dengan bunga-bunga lembut. Jantungnya kopi dan mawar berpadu intens, sebelum mengendap di amber, musk, dan vanilla yang dominan hangat. Lebih floral dan intens dibanding Praline Tonka atau Midnight Coffee, cocok dipakai malam hari.",
    notes: {
      top: ["Bunga-bunga"],
      middle: ["Kopi", "Mawar"],
      base: ["Amber", "Musk", "Vanilla"],
    },
    mainAccords: [
      { nama: "Vanilla", persen: 85 },
      { nama: "Coffee", persen: 75 },
      { nama: "Sweet", persen: 60 },
      { nama: "Floral", persen: 35 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Montale/Intense-Cafe-18021.html",
    bottleColor: "#4a2f2a",
  },
  {
    slug: "jasmine-sambac",
    nama: "Jasmine Sambac",
    grade: "Premium",
    gender: "Wanita",
    waktuPakai: ["Siang", "Sore"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "White floral murni — jasmine sambac bertemu tuberose dan cendana.",
    deskripsi:
      "Racikan white floral yang jujur dan tanpa basa-basi — jasmine sambac dan tuberose jadi jantung utamanya, dipadu rangoon creeper yang eksotis. Di dasar, cendana dan musk memberi kelembutan yang membekas. Klasik dan feminin, cocok dipakai siang ke sore.",
    notes: {
      top: ["Bunga Jeruk"],
      middle: ["Tuberose", "Melati Sambac", "Rangoon Creeper"],
      base: ["Cendana", "Musk"],
    },
    mainAccords: [
      { nama: "Floral", persen: 95 },
      { nama: "Sweet", persen: 45 },
      { nama: "Musky", persen: 35 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Gucci/Gucci-Bloom-44894.html",
    bottleColor: "#b89ab8",
  },
  {
    slug: "green-pepper-musk",
    nama: "Green Pepper Musk",
    grade: "Medium",
    gender: "Pria",
    waktuPakai: ["Pagi", "Siang"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Woody floral musk klasik — daun hijau bertemu lada dan musk bersih.",
    deskripsi:
      "Racikan woody-floral-musk klasik yang membuka dengan daun hijau, kapulaga, dan lada tajam. Jantungnya sage dan cedar, sebelum mengendap di amber dan musk yang bersih-soapy. Timeless dan mudah dipakai, cocok untuk kerja sehari-hari.",
    notes: {
      top: ["Daun Hijau", "Kapulaga", "Lada"],
      middle: ["Sage", "Cedar"],
      base: ["Amber", "Musk"],
    },
    mainAccords: [
      { nama: "Green", persen: 80 },
      { nama: "Woody", persen: 60 },
      { nama: "Musky", persen: 55 },
      { nama: "Rempah", persen: 35 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Carolina-Herrera/212-Men-297.html",
    bottleColor: "#5a6b3a",
  },
  {
    slug: "almond-heliotrope",
    nama: "Almond Heliotrope",
    grade: "Premium",
    gender: "Pria",
    waktuPakai: ["Sore", "Malam"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Oriental fougere hangat — almond pahit bertemu heliotrope bedak.",
    deskripsi:
      "Racikan oriental-fougere yang membuka dengan bergamot, heliotrope, dan cumin tajam. Jantungnya melati, bitter almond, dan lavender, sebelum mengendap di amber, vanilla, dan cendana yang manis-powdery. Bold dan intens, cocok dipakai malam hari saat cuaca dingin.",
    notes: {
      top: ["Bergamot", "Heliotrope", "Cumin"],
      middle: ["Melati", "Bitter Almond", "Lavender"],
      base: ["Amber", "Vanilla", "Cendana"],
    },
    mainAccords: [
      { nama: "Sweet", persen: 82 },
      { nama: "Amber", persen: 65 },
      { nama: "Rempah", persen: 45 },
      { nama: "Floral", persen: 30 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Parfums-de-Marly/Pegasus-16938.html",
    bottleColor: "#7c5c3a",
  },
  {
    slug: "sweet-pea-peony",
    nama: "Sweet Pea Peony",
    grade: "Medium",
    gender: "Wanita",
    waktuPakai: ["Pagi", "Siang"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Floral segar — sweet pea dan bergamot bertemu peony dan mawar.",
    deskripsi:
      "Racikan floral yang membuka dengan bergamot dan sweet pea yang hidup. Jantungnya peony dan mawar Damaskus mekar dengan anggun, sebelum mengendap di musk putih yang lembut. Ringan dan romantis, cocok dipakai pagi hingga siang.",
    notes: {
      top: ["Bergamot", "Sweet Pea"],
      middle: ["Peony", "Mawar Damaskus"],
      base: ["Musk Putih"],
    },
    mainAccords: [
      { nama: "Floral", persen: 90 },
      { nama: "Citrus", persen: 40 },
      { nama: "Musky", persen: 35 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Dior/Miss-Dior-Blooming-Bouquet-23280.html",
    bottleColor: "#d9a8b8",
  },
  {
    slug: "tuberose-agave",
    nama: "Tuberose Agave",
    grade: "Premium",
    gender: "Unisex",
    waktuPakai: ["Sore", "Malam"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "White floral eksotis — tuberose memikat bertemu agave hijau.",
    deskripsi:
      "Racikan white floral yang membuka dengan mandarin dan peach lembut. Jantungnya ylang-ylang, tuberose, dan sentuhan agave hijau-eksotis yang jadi ciri khas, sebelum mengendap di cedarwood, vanilla, tonka bean, cendana, dan musk yang hangat. Magnetis dan memorable, cocok dipakai malam hari.",
    notes: {
      top: ["Mandarin", "Peach"],
      middle: ["Ylang-Ylang", "Tuberose", "Agave"],
      base: ["Cedarwood", "Vanilla", "Tonka Bean", "Cendana", "Musk"],
    },
    mainAccords: [
      { nama: "Floral", persen: 88 },
      { nama: "Sweet", persen: 60 },
      { nama: "Woody", persen: 45 },
      { nama: "Amber", persen: 35 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Memo-Paris/Marfa-37185.html",
    bottleColor: "#c9a86a",
  },
  {
    slug: "oud-mint",
    nama: "Oud Mint",
    grade: "Premium",
    gender: "Unisex",
    waktuPakai: ["Sore", "Malam"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Woody aromatic fresh-oriental — oud hangat bertemu mint dan lemon.",
    deskripsi:
      "Racikan woody-aromatic yang membuka dengan lemon, almond, lada hitam, dan ketumbar tajam. Jantungnya oud, patchouli, melati Mesir, dan mint yang mendinginkan, sebelum mengendap di vanilla, amber, musk putih, leather, dan vetiver yang dalam. Kompleks dan hangat, cocok dipakai malam hari.",
    notes: {
      top: ["Lemon", "Almond", "Lada Hitam", "Ketumbar"],
      middle: ["Oud", "Patchouli", "Melati Mesir", "Mint"],
      base: ["Vanilla", "Amber", "Musk Putih", "Leather", "Vetiver"],
    },
    mainAccords: [
      { nama: "Woody", persen: 85 },
      { nama: "Fresh", persen: 65 },
      { nama: "Sweet", persen: 50 },
      { nama: "Rempah", persen: 35 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Mancera/Aoud-Lemon-Mint-39181.html",
    bottleColor: "#3a2a1f",
  },
  {
    slug: "sage-amberwood",
    nama: "Sage Amberwood",
    grade: "Medium",
    gender: "Pria",
    waktuPakai: ["Pagi", "Siang", "Sore"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Aromatic fougere maskulin — sage bersih bertemu amberwood dan cedar.",
    deskripsi:
      "Racikan aromatic-fougere yang membuka dengan apel, jahe, dan bergamot segar. Jantungnya sage, juniper berries, dan geranium yang bersih, sebelum mengendap di amberwood, tonka bean, cedar, vetiver, dan kemenyan yang dalam-maskulin. Serbaguna, cocok dipakai kapan saja.",
    notes: {
      top: ["Apel", "Jahe", "Bergamot"],
      middle: ["Sage", "Juniper Berries", "Geranium"],
      base: ["Amberwood", "Tonka Bean", "Cedar", "Vetiver", "Kemenyan"],
    },
    mainAccords: [
      { nama: "Woody", persen: 80 },
      { nama: "Fresh", persen: 60 },
      { nama: "Rempah", persen: 40 },
      { nama: "Amber", persen: 35 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Y-Eau-de-Parfum-50757.html",
    bottleColor: "#6b7a5a",
  },
  {
    slug: "raspberry-rose",
    nama: "Raspberry Rose",
    grade: "Premium",
    gender: "Unisex",
    waktuPakai: ["Sore", "Malam"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Amber floral mewah — raspberry dan saffron bertemu mawar dan oud.",
    deskripsi:
      "Racikan amber-floral yang membuka dengan pink pepper, raspberry, dan saffron yang tajam-manis. Jantungnya lapisan mawar — Bulgaria, Mei, dan Turki — mekar penuh, sebelum mengendap di patchouli, oud, dan benzoin yang dalam. Kontras segar dan woody-dalam, cocok dipakai malam hari.",
    notes: {
      top: ["Pink Pepper", "Raspberry", "Saffron"],
      middle: ["Mawar Bulgaria", "Mawar Mei", "Mawar Turki"],
      base: ["Patchouli", "Oud", "Benzoin"],
    },
    mainAccords: [
      { nama: "Floral", persen: 85 },
      { nama: "Amber", persen: 70 },
      { nama: "Woody", persen: 45 },
      { nama: "Fruity", persen: 30 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Louis-Vuitton/Les-Sables-Roses-55040.html",
    bottleColor: "#a83a4a",
  },
  {
    slug: "smoked-cherry",
    nama: "Smoked Cherry",
    grade: "Premium",
    gender: "Unisex",
    waktuPakai: ["Sore", "Malam"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Oriental spicy dramatis — ceri asam bertemu leather dan kayu asap.",
    deskripsi:
      "Racikan oriental-spicy yang membuka dengan ceri asam dan saffron eksotis. Jantungnya leather, osmanthus Cina, olive, dan aprikot memberi tekstur unik, sebelum mengendap di smoke, woody notes, dan cypriol yang dalam-membara. Dramatis dan memorable, cocok dipakai malam hari.",
    notes: {
      top: ["Ceri Asam", "Saffron"],
      middle: ["Leather", "Osmanthus", "Olive", "Aprikot"],
      base: ["Smoke", "Woody Notes", "Cypriol"],
    },
    mainAccords: [
      { nama: "Sweet", persen: 78 },
      { nama: "Rempah", persen: 60 },
      { nama: "Woody", persen: 55 },
      { nama: "Fruity", persen: 40 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Tom-Ford/Cherry-Smoke-78578.html",
    bottleColor: "#5a1f2a",
  },
  {
    slug: "grapefruit-jasmine",
    nama: "Grapefruit Jasmine",
    grade: "Medium",
    gender: "Wanita",
    waktuPakai: ["Pagi", "Siang"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Floral fruity ceria — grapefruit segar bertemu melati dan mawar.",
    deskripsi:
      "Racikan floral-fruity yang membuka dengan bergamot, grapefruit merah muda, cassia, mandarin, dan blackcurrant yang vibrant. Jantungnya aprikot, melati, lily, dan mawar mekar romantis, sebelum mengendap di amber, musk, tonka bean, vanilla, dan cedar. Ceria dan mudah dipakai, cocok untuk siang hari.",
    notes: {
      top: ["Bergamot", "Grapefruit", "Cassia", "Mandarin", "Blackcurrant"],
      middle: ["Aprikot", "Melati", "Lily", "Mawar"],
      base: ["Amber", "Musk", "Tonka Bean", "Vanilla", "Cedar"],
    },
    mainAccords: [
      { nama: "Fruity", persen: 85 },
      { nama: "Floral", persen: 65 },
      { nama: "Sweet", persen: 45 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Cacharel/Amor-Amor-238.html",
    bottleColor: "#d97a6a",
  },
  {
    slug: "gardenia-coffee",
    nama: "Gardenia Coffee",
    grade: "Premium",
    gender: "Unisex",
    waktuPakai: ["Sore", "Malam"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Floral oud mewah — mawar dan gardenia bertemu kopi dan cendana.",
    deskripsi:
      "Racikan floral-woody yang membuka dengan bergamot, mandarin, dan grapefruit segar. Jantungnya mawar, geranium, water lily, dan gardenia mekar penuh, sebelum mengendap di kapulaga, cendana, guaiac wood, kopi, dan musk yang mewah membekas lama. Luxurious dan kompleks, cocok untuk acara formal.",
    notes: {
      top: ["Bergamot", "Mandarin", "Grapefruit"],
      middle: ["Mawar", "Geranium", "Water Lily", "Gardenia"],
      base: ["Kapulaga", "Cendana", "Guaiac Wood", "Kopi", "Musk"],
    },
    mainAccords: [
      { nama: "Floral", persen: 80 },
      { nama: "Coffee", persen: 60 },
      { nama: "Woody", persen: 50 },
      { nama: "Amber", persen: 35 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Parfums-de-Marly/Layton-Exclusif-46633.html",
    bottleColor: "#7a5a4a",
  },
  {
    slug: "passionfruit-peony",
    nama: "Passionfruit Peony",
    grade: "Medium",
    gender: "Wanita",
    waktuPakai: ["Pagi", "Siang"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Floral fruity ceria — passion fruit dan strawberry bertemu peony.",
    deskripsi:
      "Racikan floral-fruity yang membuka dengan passion fruit, grapefruit, nanas, tangerine, dan strawberry besar yang meriah. Jantungnya peony, vanilla orchid, red berries, dan melati mekar manis, sebelum mengendap di musk, woody notes, dan oakmoss. Ceria dan fun, cocok dipakai harian.",
    notes: {
      top: ["Passion Fruit", "Grapefruit", "Nanas", "Tangerine", "Strawberry"],
      middle: ["Peony", "Vanilla Orchid", "Red Berries", "Melati"],
      base: ["Musk", "Woody Notes", "Oakmoss"],
    },
    mainAccords: [
      { nama: "Fruity", persen: 92 },
      { nama: "Floral", persen: 60 },
      { nama: "Sweet", persen: 40 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Victoria-s-Secret/Bombshell-10190.html",
    bottleColor: "#e8a83a",
  },
  {
    slug: "blackcurrant-rose",
    nama: "Blackcurrant Rose",
    grade: "Premium",
    gender: "Wanita",
    waktuPakai: ["Siang", "Sore"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Floral fruity elegan — blackcurrant dan pir bertemu mawar dan nanas.",
    deskripsi:
      "Racikan floral-fruity yang membuka dengan pir, blackcurrant, pink pepper, dan grapefruit yang segar-vigorous. Jantungnya nanas, mawar, melati, dan heliotrope mekar powerful, sebelum mengendap di vanilla, cedar, patchouli, dan amberwood yang hangat. Passionate dan elegan, cocok dipakai siang ke sore.",
    notes: {
      top: ["Pir", "Blackcurrant", "Pink Pepper", "Grapefruit"],
      middle: ["Nanas", "Mawar", "Melati", "Heliotrope"],
      base: ["Vanilla", "Cedar", "Patchouli", "Amberwood"],
    },
    mainAccords: [
      { nama: "Floral", persen: 85 },
      { nama: "Fruity", persen: 60 },
      { nama: "Sweet", persen: 45 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Giorgio-Armani/Si-Passione-48002.html",
    bottleColor: "#6b2a4a",
  },
  {
    slug: "litsea-mint",
    nama: "Litsea Mint",
    grade: "Premium",
    gender: "Pria",
    waktuPakai: ["Sore", "Malam"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Oriental fougere hangat — mint segar bertemu tonka bean dan amber.",
    deskripsi:
      "Racikan oriental-fougere yang membuka dengan mint, lemon, lada hitam, elemi, dan litsea cubeba yang tajam-segar. Jantungnya apel hijau, geranium, lavender, sage, dan pomarose, sebelum mengendap di tonka bean, amber, vanilla, patchouli, dan benzoin yang hangat-lush. Lebih dalam dan warm dibanding Mint Tonka, cocok dipakai malam hari.",
    notes: {
      top: ["Mint", "Lemon", "Lada Hitam", "Elemi", "Litsea Cubeba"],
      middle: ["Apel Hijau", "Geranium", "Lavender", "Sage", "Pomarose"],
      base: ["Tonka Bean", "Amber", "Vanilla", "Patchouli", "Benzoin"],
    },
    mainAccords: [
      { nama: "Sweet", persen: 80 },
      { nama: "Fresh", persen: 65 },
      { nama: "Amber", persen: 50 },
      { nama: "Woody", persen: 35 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Versace/Eros-Parfum-70090.html",
    bottleColor: "#4a5a3a",
  },
  {
    slug: "melon-cappuccino",
    nama: "Melon Cappuccino",
    grade: "Medium",
    gender: "Pria",
    waktuPakai: ["Pagi", "Siang"],
    hargaMulai: HARGA_MULAI_DEFAULT,
    volumeTersedia: VOLUME_TERSEDIA_DEFAULT,
    ringkasan: "Aromatic aquatic unik — melon segar bertemu cappuccino di base.",
    deskripsi:
      "Racikan aromatic-aquatic yang membuka dengan melon, bergamot, mint, dan blackcurrant yang menyegarkan. Jantungnya nutmeg, apel hijau, kapulaga, dan ocean accord, sebelum mengendap di amber, oakmoss, woods, dan cappuccino yang unik-hangat. Fresh dengan twist unexpected, cocok dipakai harian.",
    notes: {
      top: ["Melon", "Bergamot", "Mint", "Blackcurrant"],
      middle: ["Nutmeg", "Apel Hijau", "Kapulaga", "Ocean Accord"],
      base: ["Amber", "Oakmoss", "Woods", "Cappuccino"],
    },
    mainAccords: [
      { nama: "Aquatic", persen: 85 },
      { nama: "Fresh", persen: 70 },
      { nama: "Fruity", persen: 45 },
      { nama: "Woody", persen: 35 },
    ],
    fragranticaUrl: "https://www.fragrantica.com/perfume/Antonio-Banderas/Blue-Seduction-1088.html",
    bottleColor: "#4a7a8a",
  },
];

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug);
}
