export interface ReferensiRacikan {
  racikanNama: string;
  referensiBrand: string;
  referensiParfum: string;
  fragranticaUrl: string;
}

export const referensiRacikan: ReferensiRacikan[] = [
  { racikanNama: "Verdant Fig", referensiBrand: "Mykonos", referensiParfum: "Down to Earth", fragranticaUrl: "https://www.fragrantica.com/perfume/Mykonos/Down-to-Earth-120471.html" },
  { racikanNama: "Rosé Bergamot", referensiBrand: "Mykonos", referensiParfum: "Monaco Royale", fragranticaUrl: "https://www.fragrantica.com/perfume/Mykonos/Monaco-Royale-121113.html" },
  { racikanNama: "Praline Tonka", referensiBrand: "Mykonos", referensiParfum: "Cafe Drops", fragranticaUrl: "https://www.fragrantica.com/perfume/Mykonos/Cafe-Drops-120463.html" },
  { racikanNama: "Iris Amber", referensiBrand: "SAFF & Co.", referensiParfum: "Solaris", fragranticaUrl: "https://www.fragrantica.com/perfume/SAFF-Co/Solaris-98616.html" },
  { racikanNama: "Bergamot Chai", referensiBrand: "Mykonos", referensiParfum: "Inception", fragranticaUrl: "https://www.fragrantica.com/perfume/Mykonos/Inception-121107.html" },
  { racikanNama: "Apricot Rose", referensiBrand: "Mykonos", referensiParfum: "Utopia", fragranticaUrl: "https://www.fragrantica.com/perfume/Mykonos/Utopia-121138.html" },
  { racikanNama: "Lavender Marine", referensiBrand: "Mykonos", referensiParfum: "California Blue", fragranticaUrl: "https://www.fragrantica.com/perfume/Mykonos/California-Blue-120464.html" },
  { racikanNama: "Cardamom Amber", referensiBrand: "Rabanne", referensiParfum: "Black XS (2005, original)", fragranticaUrl: "https://www.fragrantica.com/perfume/Rabanne/Black-XS-514.html" },
  { racikanNama: "Bergamot Ambroxan", referensiBrand: "Dior", referensiParfum: "Sauvage (2015 EDT, original)", fragranticaUrl: "https://www.fragrantica.com/perfume/Dior/Sauvage-31861.html" },
  { racikanNama: "Cinnamon Oud", referensiBrand: "Lattafa Perfumes", referensiParfum: "Khamrah", fragranticaUrl: "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Khamrah-75805.html" },
  { racikanNama: "Ginger Ambroxan", referensiBrand: "Louis Vuitton", referensiParfum: "Imagination", fragranticaUrl: "https://www.fragrantica.com/perfume/Louis-Vuitton/Imagination-67370.html" },
  { racikanNama: "Pineapple Birch", referensiBrand: "Creed", referensiParfum: "Aventus", fragranticaUrl: "https://www.fragrantica.com/perfume/Creed/Aventus-9828.html" },
  { racikanNama: "Mint Tonka", referensiBrand: "Versace", referensiParfum: "Eros (EDT original)", fragranticaUrl: "https://www.fragrantica.com/perfume/Versace/Eros-16657.html" },
  { racikanNama: "Plum Driftwood", referensiBrand: "Rasasi", referensiParfum: "Hawas Ice", fragranticaUrl: "https://www.fragrantica.com/perfume/Rasasi/Hawas-Ice-89050.html" },
  { racikanNama: "Saffron Ambergris", referensiBrand: "Maison Francis Kurkdjian", referensiParfum: "Baccarat Rouge 540", fragranticaUrl: "https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/Baccarat-Rouge-540-33519.html" },
  { racikanNama: "Midnight Coffee", referensiBrand: "Yves Saint Laurent", referensiParfum: "Black Opium", fragranticaUrl: "https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Black-Opium-25324.html" },
  { racikanNama: "Pear Musk", referensiBrand: "Ex Nihilo", referensiParfum: "Blue Talisman", fragranticaUrl: "https://www.fragrantica.com/perfume/Ex-Nihilo/Blue-Talisman-84224.html" },
  { racikanNama: "Cherry Almond", referensiBrand: "Tom Ford", referensiParfum: "Lost Cherry", fragranticaUrl: "https://www.fragrantica.com/perfume/Tom-Ford/Lost-Cherry-51411.html" },
  { racikanNama: "Green Apple Lotus", referensiBrand: "Nautica", referensiParfum: "Nautica Voyage", fragranticaUrl: "https://www.fragrantica.com/perfume/Nautica/Nautica-Voyage-913.html" },
  { racikanNama: "Pineapple Patchouli", referensiBrand: "Nishane", referensiParfum: "Hacivat", fragranticaUrl: "https://www.fragrantica.com/perfume/Nishane/Hacivat-44174.html" },
  { racikanNama: "Lychee Rose", referensiBrand: "Parfums de Marly", referensiParfum: "Delina", fragranticaUrl: "https://www.fragrantica.com/perfume/Parfums-de-Marly/Delina-43871.html" },
  { racikanNama: "Apple Caramel", referensiBrand: "Afnan", referensiParfum: "9 PM Rebel", fragranticaUrl: "https://www.fragrantica.com/perfume/Afnan/9-PM-Rebel-99238.html" },
  { racikanNama: "Golden Ylang", referensiBrand: "Dior", referensiParfum: "J'adore", fragranticaUrl: "https://www.fragrantica.com/perfume/Dior/J-adore-210.html" },
  { racikanNama: "Velvet Rose", referensiBrand: "Parfums de Marly", referensiParfum: "Delina Exclusif", fragranticaUrl: "https://www.fragrantica.com/perfume/Parfums-de-Marly/Delina-Exclusif-50370.html" },
  { racikanNama: "Pistachio Gelato", referensiBrand: "Kayali Fragrances", referensiParfum: "Yum Pistachio Gelato | 33", fragranticaUrl: "https://www.fragrantica.com/perfume/Kayali-Fragrances/Yum-Pistachio-Gelato-33-79846.html" },
  { racikanNama: "Pear Freesia", referensiBrand: "Jo Malone London", referensiParfum: "English Pear & Freesia", fragranticaUrl: "https://www.fragrantica.com/perfume/Jo-Malone-London/English-Pear-Freesia-10314.html" },
  { racikanNama: "Hazelnut Amberwood", referensiBrand: "Rabanne", referensiParfum: "1 Million Lucky", fragranticaUrl: "https://www.fragrantica.com/perfume/Rabanne/1-Million-Lucky-48903.html" },
  { racikanNama: "Rose Espresso", referensiBrand: "Montale", referensiParfum: "Intense Cafe", fragranticaUrl: "https://www.fragrantica.com/perfume/Montale/Intense-Cafe-18021.html" },
  { racikanNama: "Jasmine Sambac", referensiBrand: "Gucci", referensiParfum: "Gucci Bloom (2017 original)", fragranticaUrl: "https://www.fragrantica.com/perfume/Gucci/Gucci-Bloom-44894.html" },
  { racikanNama: "Green Pepper Musk", referensiBrand: "Carolina Herrera", referensiParfum: "212 Men", fragranticaUrl: "https://www.fragrantica.com/perfume/Carolina-Herrera/212-Men-297.html" },
  { racikanNama: "Almond Heliotrope", referensiBrand: "Parfums de Marly", referensiParfum: "Pegasus", fragranticaUrl: "https://www.fragrantica.com/perfume/Parfums-de-Marly/Pegasus-16938.html" },
  { racikanNama: "Sweet Pea Peony", referensiBrand: "Dior", referensiParfum: "Miss Dior Blooming Bouquet", fragranticaUrl: "https://www.fragrantica.com/perfume/Dior/Miss-Dior-Blooming-Bouquet-23280.html" },
  { racikanNama: "Tuberose Agave", referensiBrand: "Memo Paris", referensiParfum: "Marfa", fragranticaUrl: "https://www.fragrantica.com/perfume/Memo-Paris/Marfa-37185.html" },
  { racikanNama: "Oud Mint", referensiBrand: "Mancera", referensiParfum: "Aoud Lemon Mint", fragranticaUrl: "https://www.fragrantica.com/perfume/Mancera/Aoud-Lemon-Mint-39181.html" },
  { racikanNama: "Sage Amberwood", referensiBrand: "Yves Saint Laurent", referensiParfum: "Y Eau de Parfum", fragranticaUrl: "https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Y-Eau-de-Parfum-50757.html" },
  { racikanNama: "Raspberry Rose", referensiBrand: "Louis Vuitton", referensiParfum: "Les Sables Roses", fragranticaUrl: "https://www.fragrantica.com/perfume/Louis-Vuitton/Les-Sables-Roses-55040.html" },
  { racikanNama: "Smoked Cherry", referensiBrand: "Tom Ford", referensiParfum: "Cherry Smoke", fragranticaUrl: "https://www.fragrantica.com/perfume/Tom-Ford/Cherry-Smoke-78578.html" },
  { racikanNama: "Grapefruit Jasmine", referensiBrand: "Cacharel", referensiParfum: "Amor Amor", fragranticaUrl: "https://www.fragrantica.com/perfume/Cacharel/Amor-Amor-238.html" },
  { racikanNama: "Gardenia Coffee", referensiBrand: "Parfums de Marly", referensiParfum: "Layton Exclusif", fragranticaUrl: "https://www.fragrantica.com/perfume/Parfums-de-Marly/Layton-Exclusif-46633.html" },
  { racikanNama: "Passionfruit Peony", referensiBrand: "Victoria's Secret", referensiParfum: "Bombshell", fragranticaUrl: "https://www.fragrantica.com/perfume/Victoria-s-Secret/Bombshell-10190.html" },
  { racikanNama: "Blackcurrant Rose", referensiBrand: "Giorgio Armani", referensiParfum: "Sì Passione", fragranticaUrl: "https://www.fragrantica.com/perfume/Giorgio-Armani/Si-Passione-48002.html" },
  { racikanNama: "Litsea Mint", referensiBrand: "Versace", referensiParfum: "Eros Parfum (2021)", fragranticaUrl: "https://www.fragrantica.com/perfume/Versace/Eros-Parfum-70090.html" },
  { racikanNama: "Melon Cappuccino", referensiBrand: "Antonio Banderas", referensiParfum: "Blue Seduction (men)", fragranticaUrl: "https://www.fragrantica.com/perfume/Antonio-Banderas/Blue-Seduction-1088.html" },
  { racikanNama: "Apple Lavender", referensiBrand: "Parfums de Marly", referensiParfum: "Layton", fragranticaUrl: "https://www.fragrantica.com/perfume/Parfums-de-Marly/Layton-39314.html" },
  { racikanNama: "Candy Apple Leather", referensiBrand: "Versace", referensiParfum: "Eros Eau de Parfum", fragranticaUrl: "https://www.fragrantica.com/perfume/Versace/Eros-Eau-de-Parfum-62762.html" },
  { racikanNama: "Lavender Tonka", referensiBrand: "Yves Saint Laurent", referensiParfum: "Libre Intense", fragranticaUrl: "https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Libre-Intense-62318.html" },
  { racikanNama: "Honey Lavender", referensiBrand: "Yves Saint Laurent", referensiParfum: "Libre Le Parfum", fragranticaUrl: "https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Libre-Le-Parfum-75676.html" },
  { racikanNama: "Grapefruit Marine", referensiBrand: "Rabanne", referensiParfum: "Invictus", fragranticaUrl: "https://www.fragrantica.com/perfume/Rabanne/Invictus-18471.html" },
  { racikanNama: "Soap Marine", referensiBrand: "Rabanne", referensiParfum: "Invictus Parfum", fragranticaUrl: "https://www.fragrantica.com/perfume/Rabanne/Invictus-Parfum-90433.html" },
  { racikanNama: "Absinthe Vanilla", referensiBrand: "Carolina Herrera", referensiParfum: "212 VIP Black", fragranticaUrl: "https://www.fragrantica.com/perfume/Carolina-Herrera/212-VIP-Black-46093.html" },
  { racikanNama: "Sea Salt Sage", referensiBrand: "Jo Malone London", referensiParfum: "Wood Sage & Sea Salt", fragranticaUrl: "https://www.fragrantica.com/perfume/Jo-Malone-London/Wood-Sage-Sea-Salt-25529.html" },
  { racikanNama: "Petitgrain Oakmoss", referensiBrand: "Parfums de Marly", referensiParfum: "Greenley", fragranticaUrl: "https://www.fragrantica.com/perfume/Parfums-de-Marly/Greenley-62101.html" },
  { racikanNama: "Saffron Rose", referensiBrand: "Mancera", referensiParfum: "Instant Crush", fragranticaUrl: "https://www.fragrantica.com/perfume/Mancera/Instant-Crush-54885.html" },
  { racikanNama: "Grapefruit Incense", referensiBrand: "Chanel", referensiParfum: "Bleu de Chanel (EDT 2010)", fragranticaUrl: "https://www.fragrantica.com/perfume/Chanel/Bleu-de-Chanel-9099.html" },
  { racikanNama: "Magnolia Clove", referensiBrand: "Moschino", referensiParfum: "Toy Boy", fragranticaUrl: "https://www.fragrantica.com/perfume/Moschino/Toy-Boy-55858.html" },
  { racikanNama: "Passionfruit Heliotrope", referensiBrand: "Tiziana Terenzi", referensiParfum: "Kirke", fragranticaUrl: "https://www.fragrantica.com/perfume/Tiziana-Terenzi/Kirke-32172.html" },
  { racikanNama: "Violet Patchouli", referensiBrand: "Yves Saint Laurent", referensiParfum: "Tuxedo", fragranticaUrl: "https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Tuxedo-32269.html" },
  { racikanNama: "Sweet Oud", referensiBrand: "Lattafa Perfumes", referensiParfum: "Ameer Al Oudh Intense Oud", fragranticaUrl: "https://www.fragrantica.com/perfume/Lattafa-Perfumes/Ameer-Al-Oudh-Intense-Oud-64947.html" },
  { racikanNama: "Almond Lotus", referensiBrand: "Parfums de Marly", referensiParfum: "Valaya Exclusif", fragranticaUrl: "https://www.fragrantica.com/perfume/Parfums-de-Marly/Valaya-Exclusif-102806.html" },
  { racikanNama: "Strawberry Peony", referensiBrand: "Yves Saint Laurent", referensiParfum: "Mon Paris", fragranticaUrl: "https://www.fragrantica.com/perfume/Yves-Saint-Laurent/Mon-Paris-38914.html" },
  { racikanNama: "Honey Gardenia", referensiBrand: "Jean Paul Gaultier", referensiParfum: "Scandal (women)", fragranticaUrl: "https://www.fragrantica.com/perfume/Jean-Paul-Gaultier/Scandal-45651.html" },
  { racikanNama: "Mirabelle Freesia", referensiBrand: "Chloé", referensiParfum: "Nomade", fragranticaUrl: "https://www.fragrantica.com/perfume/Chloe/Nomade-48434.html" },
  { racikanNama: "Salty Vanilla", referensiBrand: "Rabanne", referensiParfum: "Olympea (original 2015)", fragranticaUrl: "https://www.fragrantica.com/perfume/Rabanne/Olympea-31666.html" },
  { racikanNama: "Raspberry Leather", referensiBrand: "Tom Ford", referensiParfum: "Tuscan Leather", fragranticaUrl: "https://www.fragrantica.com/perfume/Tom-Ford/Tuscan-Leather-1849.html" },
  { racikanNama: "Sparkling Lychee", referensiBrand: "Kayali Fragrances", referensiParfum: "Eden Sparkling Lychee | 39", fragranticaUrl: "https://www.fragrantica.com/perfume/Kayali-Fragrances/Eden-Sparkling-Lychee-39-Eau-de-Parfum-88197.html" },
  { racikanNama: "Violet Tobacco", referensiBrand: "Tom Ford", referensiParfum: "Ombré Leather Parfum", fragranticaUrl: "https://www.fragrantica.com/perfume/Tom-Ford/Ombre-Leather-Parfum-68716.html" },
  { racikanNama: "Bluebell Persimmon", referensiBrand: "Jo Malone London", referensiParfum: "Wild Bluebell (original 2011)", fragranticaUrl: "https://www.fragrantica.com/perfume/Jo-Malone-London/Wild-Bluebell-12310.html" },
  { racikanNama: "Saffron Vetiver", referensiBrand: "Byredo", referensiParfum: "Black Saffron", fragranticaUrl: "https://www.fragrantica.com/perfume/Byredo/Black-Saffron-16220.html" },
  { racikanNama: "Passion Vanilla", referensiBrand: "Lancôme", referensiParfum: "Hypnose", fragranticaUrl: "https://www.fragrantica.com/perfume/Lancome/Hypnose-170.html" },
];
